---
title: "Data 607 Context Presentation"
author: "Ajay Arora"
date: "October 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Step 1 : Source file

# Step 2 : Install and load the required packages
## Install
```{r}
#install.packages("tm")  # for text mining
#install.packages("SnowballC") # for text stemming
#install.packages("wordcloud") # word-cloud generator 
#install.packages("RColorBrewer") # color palettes
```
## Load
```{r}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```

## Read the text file from repository
```{r}
filePath <- "https://raw.githubusercontent.com/AjayArora35/Data-607-Context-Presentation/master/sample.txt"
text <- readLines(filePath)

```

## Load the data as corpus
```{r}
# Load the data as a corpus
docs <- Corpus(VectorSource(text))

```

## Quick Inspection
```{r}
inspect(docs)
```

# Transform Text
```{r}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

```

# Cleaning Text
```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```

#Step 4 : Build a term-document matrix
```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```

#Step 5 : Generate the Word cloud
```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```